### ISSUE TITLE
Which drone to choose

### ISSUE THREAD

**Issue by vovaklh** [DragonX-cloud/dji_flutter_plugin#1]
Hi! I want to try your package with DJI Mini 2. Can I do this?

**Comment by orenagiv** [comment]
Hey @vovaklh 
(Sorry for my late reply...)

Until just a few days ago, the DJI Mini 2 was not supported by the DJI iOS Mobile SDK.
But it seems that their latest version supports it now:
https://dronedj.com/2022/03/13/dji-ios-mobile-sdk-mini-2-air-2s-drone/

Please give it a try and let me know if it worked.

P.S.
Please note the dji_flutter_plugin is still under development.

**Comment by orenagiv** [comment]
I'm attempting to upgrade to the plugin to use DJI SDK 4.16 (iOS) and 4.16.1 (Android) now.
It will probably not work on the first attempt :) 
But I'll keep you posted.

**Comment by vovaklh** [comment]
Thank you!
I will try your plugin when I buy drone.

**Comment by orenagiv** [comment]
The plugin has been updated with DJI SDK 4.16.
Closing.
