### ISSUE TITLE
Drones compatibility

### ISSUE THREAD

**Issue by vovaklh** [DragonX-cloud/dji_flutter_plugin#16]
Hi!
Is this sdk is compatible with all Dji drones? For example, with Dji mini se.

**Comment by orenagiv** [comment]
Hey @vovaklh 
This Flutter plugin is using the DJI SDK Mobile v4, which supports both the smaller drones of DJI (e.g. Mavic, Mini, etc.) as well as their larger drones (+ it supports both Android and iOS):
https://developer.dji.com/mobile-sdk-v4/

This is the DJI SDKs v4 of iOS and Android, which this plugin is using:
https://github.com/dji-sdk/Mobile-SDK-iOS
https://github.com/dji-sdk/Mobile-SDK-Android

The supported DJI Drones by the above SDKs are described by DJI here:
https://developer.dji.com/
(Scroll down to Mobile SDK and choose the iOS or Android v4.16.x tabs)

For iOS - these are the supported drones by DJI Mobile SDK v4.16:
DJI Mini 2, DJI Mini SE, DJI Air 2S, Mavic Air 2, Mavic Mini, Matrice 300 RTK, Matrice 200 V2, Matrice 210 V2, Matrice 210 RTK V2, Phantom 4 RTK, Mavic 2 Enterprise, Mavic 2 Enterprise Dual, Mavic 2 Pro, Mavic 2 Zoom.

For Android - these are the supported drones by DJI Mobile SDK v4.16:
DJI Mini 2, DJI Mini SE, DJI Air 2S, Mavic 2 Enterprise Advanced, Mavic Air 2, Mavic Mini, Matrice 300 RTK, Matrice 200 V2, Matrice 210 V2, Matrice 210 RTK V2, Phantom 4 RTK, Mavic 2 Enterprise, Mavic 2 Enterprise Dual, Mavic 2 Pro, Mavic 2 Zoom.

Please note that this Flutter plugin has only been tested with Mavic Air so far.
So I anticipate connection issues with other drones.
However, please feel free to open an issue here in this Github repo in case you encounter issues with the DJI Mini.

**Note**
DJI recently release their DJI SDK v5, however, it only supports the Enterprise and "industrial" drones so far + it's only for Android.

**Comment by vovaklh** [comment]
@orenagiv 
Thank you for this awesome response! Have a nice day!
