### ISSUE TITLE
DJI app integration with Drone Controller Failure. 

### ISSUE THREAD

**Issue by kbattulwar** [DragonX-cloud/dji_flutter_plugin#17]
Hi, 
I am using flutter DJI sdk in my android app.I am trying to integrate the application with the controller using the data cable. But it doesn't seem to work. Can anyone help me to fix this issue? 
Thank you

**Comment by orenagiv** [comment]
Hey @kbattulwar 
I'll need much more details to assist you here 🙂 

Can you please share full details?

**Comment by kbattulwar** [comment]
Hi Oren,
Thank You for responding, I really appreciate your time.I am a grad student
at UNR Reno. I was trying to build a project using dji mobile SDK. I  got
the SDK from GitHub and integrated it into android studio. I ran the app
into my Samsung galaxy A8 star. After finishing the upload I tried to load
the and the app loaded successfully. Then next step was to connect the
application to the drone controller. We have a dji inspire drone with us. I
used a USB cable to connect my smartphone which has the application to the
drone controller. It has various buttons on the interface. I tried
registering the app by hitting the register app button but there was no
response. If I hit any button in the app it's not connecting to the
controller. Could you please, let me know how can I establish
a successful connection with the app to the drone so that, I can use the
application for flying the drone?
I look forward to hearing from you.


Thank You

**Comment by orenagiv** [comment]
Hey @kbattulwar 
Did you follow all the step-by-step configuration instructions in the Readme of this plugin?
Are you able to successfully connect to the Drone using the native DJI GO app?

**Comment by orenagiv** [comment]
Hey @kbattulwar 
I'm closing this issue for now due to lack of info.
