### ISSUE TITLE
Register app

### ISSUE THREAD

**Issue by Tiaan3dts** [DragonX-cloud/dji_flutter_plugin#19]
When running the example folder as is the build succeeds, however I get the following error: 

I/flutter: PlatformException(NoClassDefFoundError, java.lang.NoClassDefFoundError: Failed resolution of: Ldji/sdk/sdkmanager/DJISDKManager$SDKManagerCallback;, Cause: java.lang.ClassNotFoundException: Didn't find class "dji.sdk.sdkmanager.DJISDKManager$SDKManagerCallback" on path: DexPathList[[zip file "/data/app/~~6dPT2pycYn6fZZhJweqsXA==/cloud.dragonx.plugin.flutter.djiExample-tioLk4Hdfq8EZdih8vH-sQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~6dPT2pycYn6fZZhJweqsXA==/cloud.dragonx.plugin.flutter.djiExample-tioLk4Hdfq8EZdih8vH-sQ==/lib/arm64, /data/app/~~6dPT2pycYn6fZZhJweqsXA==/cloud.dragonx.plugin.flutter.djiExample-tioLk4Hdfq8EZdih8vH-sQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]], Stacktrace: java.lang.NoClassDefFoundError: Failed resolution of: Ldji/sdk/sdkmanager/DJISDKManager$SDKManagerCallback;
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:24)
        at java.lang.reflect.Method.invoke(Native Method)
    	at io.flutter.embedding.engine.plugins.util.G

The android version is 13, jdk 11 and I am testing on a actual android device.

**Comment by orenagiv** [comment]
Hey @Tiaan3dts 
Did you build the Example via Android Studio? Or VSCode?
Did you simply execute "flutter run"?

To isolate the problem - please open the actual Android project (/example/android) in Android Studio, and attempt to build it onto your Android device from there.

**Comment by orenagiv** [comment]
Hey @Tiaan3dts,
I'm closing this issue since you've not responded.
But if you have more details - please reply and I'll re-open.
