### ISSUE TITLE
Does this plugin work with the new SDK 5?

### ISSUE THREAD

**Issue by The-Michael-Chen** [DragonX-cloud/dji_flutter_plugin#23]
I have the DJI Mini 3 and want to ensure using this repository will still work. I know the DJI Mini 3 is supported by the SDK v5

**Comment by orenagiv** [comment]
Hi @The-Michael-Chen 
Unfortunately, DJI SDK 5 is only for Android... so I haven't found it useful to wrap as a Flutter plugin.
