### ISSUE TITLE
Live video feed not working

### ISSUE THREAD

**Issue by The-Michael-Chen** [DragonX-cloud/dji_flutter_plugin#24]
Example app live video feed doesn't work for android 13

**Comment by orenagiv** [comment]
Hey @The-Michael-Chen,

Which `targetSdk` is configured in your `build.gradle` file?

Please also review the discussion here about Android 13:
https://github.com/DragonX-cloud/dji_flutter_plugin/issues/22

**Comment by The-Michael-Chen** [comment]
The target.SDK is 31. To give some more details, the app ran great, everything works but the live stream doesn't connect.

**Comment by orenagiv** [comment]
Hmm... 🤔
Do you see any errors in the logs?
Which Drone and which device are you testing with?

**Comment by The-Michael-Chen** [comment]
It says video start failed, i'm testing with the Mini 2 drone and the Moto g stylus 2023. 
In the logs the only error I see is "lambda$getWifiLinkLayerStats_1_5_Internal$3(l.0) failed {.code = ERROR_UNKNOWN, .description = unknown}"

**Comment by The-Michael-Chen** [comment]
i also tested with the galaxy A13 and got the same exact issue!

**Comment by The-Michael-Chen** [comment]
i haven't made any edits to the example code! I'm just running it out of the box from a github clone

**Comment by orenagiv** [comment]
And your device is connected by cable to the remote control of the Drone? Or via WiFi directly to the Drone?

**Comment by The-Michael-Chen** [comment]
It's connected via cable to the remote controller of the drone

**Comment by orenagiv** [comment]
Hey @The-Michael-Chen 
I'll attempt to reproduce as soon as I can and get back to you. 
(It might take some time)

**Comment by orenagiv** [comment]
Hey @The-Michael-Chen 

Can you please attempt the following?
1. Open the ./example/android project in Android Studio.
2. Open the "LogCat" tab in the Android Studio.
2. Run the app in debug mode.
3. Once the app loads - click Register > then Connect > then Delegate.
4. Once it's "Delegated" - click the Start Video Feed button.
5. Send me the logs from the LogCat.

Thanks!

**Comment by orenagiv** [comment]
Hey @The-Michael-Chen 
Please note I've just pushed v1.0.13 which includes an updated DJI Mobile SDK for Android (v4.17).
Please fetch the latest plugin from pub.dev and give it a shot:  
https://pub.dev/packages/dji

I've tested on both Android 12 and Android 13 (with DJI Mavic Air) and the live feed worked for me on both.

In any case, assuming the latest version (v1.0.13) still won't work for you - then please try what I wrote in my previous post and send me the logs.

**Comment by orenagiv** [comment]
Hey @The-Michael-Chen 
I hope you got my last message above.
I'm closing for now.
