### ISSUE TITLE
[Question] Running app directly on a Smart Controller instead of connecting via a cable?

### ISSUE THREAD

**Issue by brandon-watkins-avcrm** [DragonX-cloud/dji_flutter_plugin#25]
I just wanted to know if the example app (APK) was installed directly on a Smart Controller, if it would work the same as if it was installed on a mobile device connected to a controller via a data cable?

Has this been tested before? If so, is there any additional information I would need

Thanks in advance

**Comment by orenagiv** [comment]
Hey @brandon-watkins-avcrm 

I think it should be possible to run your Flutter app on the DJI Smart Controller.

I've searched a bit in Google and found this:
https://forum.dji.com/thread-248937-1-1.html

So I suppose that the Flutter app with the plugin would work the same as connecting a mobile to the remote by cable. 

I haven't tested such a thing though.
