### ISSUE TITLE
Upgrading DJI Mobile SDK 4 to DJI Mobile SDK 5

### ISSUE THREAD

**Issue by IakovlevAA** [DragonX-cloud/dji_flutter_plugin#27]
Hi, do you have any plans to change version of SDK? As I know, version 4 doesn't work with new dji drones

**Comment by orenagiv** [comment]
Hey @IakovlevAA 

Yes, I'm going to create another DJI Flutter Plugin for SDK 5.
However, I'm not sure yet when...
(Please note the Mobile SDK 5 of DJI only supports Android at this point, and it doesn't seem they have any plans to support IOS, so the plugin will also be relevant only for Flutter on Android).
