### ISSUE TITLE
Video streaming

### ISSUE THREAD

**Issue by promistrio** [DragonX-cloud/dji_flutter_plugin#3]
What prevents us from implementing video streaming now? We are interested in this feature and we can try to take part in its development.

**Comment by orenagiv** [comment]
Hey @promistrio,

I'm currently working on the "download all" feature first, but my progress is very slow as this is a personal side project.
But you're most welcome to take part and implement the streaming :)

Please feel free to fork and once you have something working to submit a pull-request > and I'll test and merge.

**Comment by orenagiv** [comment]
@promistrio,
Please note that I'm currently following this tutorial:
https://riis.com/blog/dji-sdk-tutorial-creating-a-media-manager-application/
(Github: https://github.com/godfreynolan/MediaManagerSwift)

I'm planning to add both the ability to download and preview.

**Comment by orenagiv** [comment]
Hey @promistrio,
I've just finished to add the ability to download media (v1.0.0-dev.12).
Very basic at this point, and currently only for iOS (still work-in-progress).

But I'm closing this issue for now, as the progress is being made towards full download capabilities on both Android and iOS, as well as streaming later on.

**Comment by orenagiv** [comment]
Hey @promistrio 
Almost there 🙂

Please note my last comment here:
https://github.com/DragonX-cloud/dji_flutter_plugin/issues/4#issuecomment-1120228603
