### ISSUE TITLE
您好 请教您 rc pro 带屏 遥控器 无法连接的问题

### ISSUE THREAD

**Issue by xiaoma13** [DragonX-cloud/dji_flutter_plugin#5]
我是使用rc pro 带屏 遥控器
使用您开发的 插件  无法连接到无人机

**Comment by orenagiv** [comment]
Hey @xiaoma13 
Can you please provide full-details on the issue? (in English please :))
Did you follow all the instructions in the readme?

Which drone are you using?

**Comment by orenagiv** [comment]
Closing due to no response.
